

import java.awt.BorderLayout;
import java.awt.Color;
import static java.awt.Color.white;
import java.awt.Image;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
import org.knowm.xchart.QuickChart;
import org.knowm.xchart.XChartPanel;
import org.knowm.xchart.XYChart;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author User
 */
public class UserInterface1 extends javax.swing.JFrame {

    /**
     * Creates new form UserInterface1
     */
    public UserInterface1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        Background = new javax.swing.JPanel();
        dashboard = new javax.swing.JPanel();
        selectFilesLabel = new javax.swing.JLabel();
        analyzeDataLabel = new javax.swing.JLabel();
        subjectData = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        graphLayout1 = new javax.swing.JPanel();
        graphLayout3 = new javax.swing.JPanel();
        plot1 = new javax.swing.JButton();
        plot2 = new javax.swing.JButton();
        plot3 = new javax.swing.JButton();
        plot4 = new javax.swing.JButton();
        graphLayout4 = new javax.swing.JPanel();
        graphLayout2 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        flexion1 = new javax.swing.JRadioButton();
        adduction1 = new javax.swing.JRadioButton();
        rotation1 = new javax.swing.JRadioButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        flexion2 = new javax.swing.JRadioButton();
        adduction2 = new javax.swing.JRadioButton();
        rotation2 = new javax.swing.JRadioButton();
        jComboBox4 = new javax.swing.JComboBox<>();
        flexion4 = new javax.swing.JRadioButton();
        adduction4 = new javax.swing.JRadioButton();
        rotation4 = new javax.swing.JRadioButton();
        jComboBox3 = new javax.swing.JComboBox<>();
        rotation3 = new javax.swing.JRadioButton();
        flexion3 = new javax.swing.JRadioButton();
        adduction3 = new javax.swing.JRadioButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1920, 1080));

        Background.setBackground(new java.awt.Color(204, 204, 204));
        Background.setPreferredSize(new java.awt.Dimension(1920, 1080));

        dashboard.setBackground(new java.awt.Color(191, 30, 46));

        selectFilesLabel.setBackground(new java.awt.Color(255, 204, 204));
        selectFilesLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        selectFilesLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search_icon.png"))); // NOI18N
        selectFilesLabel.setText("Select Files");
        selectFilesLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selectFilesLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                selectFilesLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                selectFilesLabelMouseExited(evt);
            }
        });

        analyzeDataLabel.setBackground(new java.awt.Color(255, 204, 204));
        analyzeDataLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        analyzeDataLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/analayze_icon.png"))); // NOI18N
        analyzeDataLabel.setText("Analyze Data");
        analyzeDataLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                analyzeDataLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                analyzeDataLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                analyzeDataLabelMouseExited(evt);
            }
        });

        subjectData.setBackground(new java.awt.Color(255, 204, 204));
        subjectData.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        subjectData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/report.png"))); // NOI18N
        subjectData.setText("Generate A Report");
        subjectData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                subjectDataMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                subjectDataMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                subjectDataMouseExited(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/shimmer.png"))); // NOI18N

        javax.swing.GroupLayout dashboardLayout = new javax.swing.GroupLayout(dashboard);
        dashboard.setLayout(dashboardLayout);
        dashboardLayout.setHorizontalGroup(
            dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(subjectData, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(analyzeDataLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(selectFilesLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        dashboardLayout.setVerticalGroup(
            dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectFilesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(analyzeDataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subjectData, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout graphLayout1Layout = new javax.swing.GroupLayout(graphLayout1);
        graphLayout1.setLayout(graphLayout1Layout);
        graphLayout1Layout.setHorizontalGroup(
            graphLayout1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        graphLayout1Layout.setVerticalGroup(
            graphLayout1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 447, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout graphLayout3Layout = new javax.swing.GroupLayout(graphLayout3);
        graphLayout3.setLayout(graphLayout3Layout);
        graphLayout3Layout.setHorizontalGroup(
            graphLayout3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        graphLayout3Layout.setVerticalGroup(
            graphLayout3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 554, Short.MAX_VALUE)
        );

        plot1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        plot1.setText("PLOT");
        plot1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plot1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                plot1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                plot1MouseExited(evt);
            }
        });
        plot1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plot1ActionPerformed(evt);
            }
        });

        plot2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        plot2.setText("PLOT");
        plot2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                plot2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                plot2MouseExited(evt);
            }
        });
        plot2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plot2ActionPerformed(evt);
            }
        });

        plot3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        plot3.setText("PLOT");
        plot3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                plot3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                plot3MouseExited(evt);
            }
        });
        plot3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plot3ActionPerformed(evt);
            }
        });

        plot4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        plot4.setText("PLOT");
        plot4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                plot4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                plot4MouseExited(evt);
            }
        });
        plot4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plot4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout graphLayout4Layout = new javax.swing.GroupLayout(graphLayout4);
        graphLayout4.setLayout(graphLayout4Layout);
        graphLayout4Layout.setHorizontalGroup(
            graphLayout4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        graphLayout4Layout.setVerticalGroup(
            graphLayout4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 447, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout graphLayout2Layout = new javax.swing.GroupLayout(graphLayout2);
        graphLayout2.setLayout(graphLayout2Layout);
        graphLayout2Layout.setHorizontalGroup(
            graphLayout2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        graphLayout2Layout.setVerticalGroup(
            graphLayout2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Left Hip", "Right Hip", "Left Knee", "Right Knee", "Left Ankle", "Right Ankle" }));
        jComboBox1.setSelectedItem(jComboBox1);
        jComboBox1.setBorder(null);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        flexion1.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(flexion1);
        flexion1.setText("Flexion/extension");
        flexion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flexion1ActionPerformed(evt);
            }
        });

        adduction1.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(adduction1);
        adduction1.setText("Abduction/Adduction");
        adduction1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adduction1ActionPerformed(evt);
            }
        });

        rotation1.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(rotation1);
        rotation1.setText("Inte/Ext Rotation");
        rotation1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rotation1ActionPerformed(evt);
            }
        });

        jComboBox2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Left Hip", "Right Hip", "Left Knee", "Right Knee", "Left Ankle", "Right Ankle" }));
        jComboBox2.setBorder(null);
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        flexion2.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup2.add(flexion2);
        flexion2.setText("Flexion/extension");
        flexion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flexion2ActionPerformed(evt);
            }
        });

        adduction2.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup2.add(adduction2);
        adduction2.setText("Abduction/Adduction");
        adduction2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adduction2ActionPerformed(evt);
            }
        });

        rotation2.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup2.add(rotation2);
        rotation2.setText("Inte/Ext Rotation");
        rotation2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rotation2ActionPerformed(evt);
            }
        });

        jComboBox4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Left Hip", "Right Hip", "Left Knee", "Right Knee", "Left Ankle", "Right Ankle" }));
        jComboBox4.setBorder(null);
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });

        flexion4.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup3.add(flexion4);
        flexion4.setText("Flexion/extension");
        flexion4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flexion4ActionPerformed(evt);
            }
        });

        adduction4.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup3.add(adduction4);
        adduction4.setText("Abduction/Adduction");
        adduction4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adduction4ActionPerformed(evt);
            }
        });

        rotation4.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup3.add(rotation4);
        rotation4.setText("Inte/Ext Rotation");
        rotation4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rotation4ActionPerformed(evt);
            }
        });

        jComboBox3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Left Hip", "Right Hip", "Left Knee", "Right Knee", "Left Ankle", "Right Ankle" }));
        jComboBox3.setBorder(null);
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        rotation3.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup4.add(rotation3);
        rotation3.setText("Inte/Ext Rotation");
        rotation3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rotation3ActionPerformed(evt);
            }
        });

        flexion3.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup4.add(flexion3);
        flexion3.setText("Flexion/extension");
        flexion3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flexion3ActionPerformed(evt);
            }
        });

        adduction3.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup4.add(adduction3);
        adduction3.setText("Abduction/Adduction");
        adduction3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adduction3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addComponent(dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(graphLayout2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(graphLayout4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(flexion1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(adduction1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rotation1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(plot1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(flexion3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(adduction3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rotation3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(plot2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(flexion2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(adduction2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rotation2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(plot3, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))
                    .addComponent(graphLayout3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(flexion4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(adduction4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rotation4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(plot4, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))
                    .addComponent(graphLayout1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(flexion2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rotation2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adduction2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plot3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(flexion1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rotation1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adduction1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plot1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(graphLayout4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(graphLayout1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(flexion4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rotation4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(plot4))
                    .addComponent(adduction4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(flexion3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rotation3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(plot2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(adduction3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(graphLayout3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(graphLayout2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectFilesLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectFilesLabelMouseClicked
        // TODO add your handling code here:
        FileChooser.fileAssign(FileChooser.fileChoose());
    }//GEN-LAST:event_selectFilesLabelMouseClicked

    private void selectFilesLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectFilesLabelMouseEntered
        // TODO add your handling code here:
        selectFilesLabel.setForeground(Color.white);
        
        //ImageIcon icon = createImageIcon("C:\\Users\\User\\OneDrive\\Documents\\NetBeansProjects\\ShimmerGraphPlotter\\src\\images\\search_icon_white.png");
        //Image img = icon.getImage();
        //Image newimg = img.getScaledInstance(selectFilesLabel.getWidth(), selectFilesLabel.getHeight(), java.awt.Image.SCALE_SMOOTH);
        //icon = new ImageIcon(newimg);
        //selectFilesLabel.setIcon(img);
    }//GEN-LAST:event_selectFilesLabelMouseEntered

    private void analyzeDataLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_analyzeDataLabelMouseClicked
        try {
            // TODO add your handling code here:
            DataAnalyze.graphPlotter(FileChooser.ref,FileChooser.lHip,"leftHip");
            DataAnalyze.graphPlotter(FileChooser.ref,FileChooser.rHip,"rightHip");
            DataAnalyze.graphPlotter(FileChooser.lHip,FileChooser.lKnee,"leftKnee");
            DataAnalyze.graphPlotter(FileChooser.rHip,FileChooser.rKnee,"rightKnee");
            DataAnalyze.graphPlotter(FileChooser.lKnee,FileChooser.lAnkle,"leftAnkle");
            DataAnalyze.graphPlotter(FileChooser.lKnee,FileChooser.lAnkle,"rightAnkle");
            
        } catch (IOException ex) {
            Logger.getLogger(UserInterface1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_analyzeDataLabelMouseClicked

    private void analyzeDataLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_analyzeDataLabelMouseEntered
        // TODO add your handling code here:
        analyzeDataLabel.setForeground(Color.white);
    }//GEN-LAST:event_analyzeDataLabelMouseEntered

    private void analyzeDataLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_analyzeDataLabelMouseExited
        // TODO add your handling code here:
        analyzeDataLabel.setForeground(Color.black);
    }//GEN-LAST:event_analyzeDataLabelMouseExited

    private void selectFilesLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectFilesLabelMouseExited
        // TODO add your handling code here:
        selectFilesLabel.setForeground(Color.black);

    }//GEN-LAST:event_selectFilesLabelMouseExited

    private void subjectDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subjectDataMouseClicked
        // TODO add your handling code here:
        new UserData().setVisible(true);
    }//GEN-LAST:event_subjectDataMouseClicked

    private void subjectDataMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subjectDataMouseEntered
        // TODO add your handling code here:
        subjectData.setForeground(Color.white);
    }//GEN-LAST:event_subjectDataMouseEntered

    private void subjectDataMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subjectDataMouseExited
        // TODO add your handling code here:
        subjectData.setForeground(Color.black);
    }//GEN-LAST:event_subjectDataMouseExited

    private void plot1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plot1ActionPerformed
        // TODO add your handling code here:
        if (jComboBox1.getSelectedItem().toString()== "Left Hip"){
            if (flexion1.isSelected()){
                //graphLayout1.set
            }
            else if (adduction1.isSelected()){
            
            }
            else if (rotation1.isSelected()){
            
            }
        }
        else if (jComboBox1.getSelectedItem().toString()== "Right Hip"){
            if (flexion1.isSelected()){
                
            }
            else if (adduction1.isSelected()){
            
            }
            else if (rotation1.isSelected()){
            
            }
        }
        else if (jComboBox1.getSelectedItem().toString()== "Left Knee"){
            if (flexion1.isSelected()){
                
            }
            else if (adduction1.isSelected()){
            
            }
            else if (rotation1.isSelected()){
            
            }
        }
        else if (jComboBox1.getSelectedItem().toString()== "Right Knee"){
            if (flexion1.isSelected()){
                
            }
            else if (adduction1.isSelected()){
            
            }
            else if (rotation1.isSelected()){
            
            }
        }
        else if (jComboBox1.getSelectedItem().toString()== "Left Ankle"){
            if (flexion1.isSelected()){
                
            }
            else if (adduction1.isSelected()){
            
            }
            else if (rotation1.isSelected()){
            
            }
        }
        else if (jComboBox1.getSelectedItem().toString()== "Right Ankle"){
            if (flexion1.isSelected()){
                
            }
            else if (adduction1.isSelected()){
            
            }
            else if (rotation1.isSelected()){
            
            }
        }
        
        
    }//GEN-LAST:event_plot1ActionPerformed

    private void plot1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plot1MouseEntered
        // TODO add your handling code here:
        Color clr1 = new Color(191,30,46);
        plot1.setBackground(clr1);
        plot1.setForeground(Color.white);
    }//GEN-LAST:event_plot1MouseEntered

    private void plot1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plot1MouseExited
        // TODO add your handling code here:
        Color clr1 = new Color(240,240,240);
        plot1.setBackground(clr1);
        plot1.setForeground(Color.black);
    }//GEN-LAST:event_plot1MouseExited

    private void plot2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plot2ActionPerformed
        // TODO add your handling code here:
        ArrayList<float[]> angles = AngleCalc.angle(FileChooser.ref, FileChooser.rHip);
        double[] xData = new double[angles.size()];
        double[] yData = new double[angles.size()];
        for (int i = 0; i < angles.size(); i++) {
            yData[i] = angles.get(i)[0];
            xData[i] = i;

        }
        XYChart chart = QuickChart.getChart("Sample Chart", "X", "Y", "y(x)", xData, yData);// Show it
        JPanel panel = new XChartPanel<>(chart);
        graphLayout1.setLayout(new BorderLayout());
        graphLayout1.add(panel);
        graphLayout1.validate();

        double[] y1Data = new double[angles.size()];
        for (int i = 0; i < angles.size(); i++) {
            y1Data[i] = angles.get(i)[1];
            xData[i] = i;

        }
        XYChart chart1 = QuickChart.getChart("Sample Chart", "X", "Y", "y(x)", xData, y1Data);// Show it
        JPanel panel1 = new XChartPanel<>(chart1);
        graphLayout2.setLayout(new BorderLayout());
        graphLayout2.add(panel1);
        graphLayout2.validate();

        double[] y2Data = new double[angles.size()];
        for (int i = 0; i < angles.size(); i++) {
            y2Data[i] = angles.get(i)[2];
            xData[i] = i;

        }
        XYChart chart2 = QuickChart.getChart("Sample Chart", "X", "Y", "y(x)", xData, y2Data);// Show it
        JPanel panel2 = new XChartPanel<>(chart2);
        graphLayout3.setLayout(new BorderLayout());
        graphLayout3.add(panel2);
        graphLayout3.validate();
    }//GEN-LAST:event_plot2ActionPerformed

    private void plot2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plot2MouseEntered
        // TODO add your handling code here:
        Color clr1 = new Color(191,30,46);
        plot2.setBackground(clr1);
        plot2.setForeground(Color.white);
    }//GEN-LAST:event_plot2MouseEntered

    private void plot2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plot2MouseExited
        // TODO add your handling code here:
        Color clr1 = new Color(240,240,240);
        plot2.setBackground(clr1);
        plot2.setForeground(Color.black);
    }//GEN-LAST:event_plot2MouseExited

    private void plot3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plot3ActionPerformed
        // TODO add your handling code here:
        ArrayList<float[]> angles = AngleCalc.angle(FileChooser.lHip, FileChooser.lKnee);
        double[] xData = new double[angles.size()];
        double[] yData = new double[angles.size()];
        for (int i = 0; i < angles.size(); i++) {
            yData[i] = angles.get(i)[0];
            xData[i] = i;

        }
        XYChart chart = QuickChart.getChart("Sample Chart", "X", "Y", "y(x)", xData, yData);// Show it
        JPanel panel = new XChartPanel<>(chart);
        graphLayout1.setLayout(new BorderLayout());
        graphLayout1.add(panel);
        graphLayout1.validate();

        double[] y1Data = new double[angles.size()];
        for (int i = 0; i < angles.size(); i++) {
            y1Data[i] = angles.get(i)[1];
            xData[i] = i;

        }
        XYChart chart1 = QuickChart.getChart("Sample Chart", "X", "Y", "y(x)", xData, y1Data);// Show it
        JPanel panel1 = new XChartPanel<>(chart1);
        graphLayout2.setLayout(new BorderLayout());
        graphLayout2.add(panel1);
        graphLayout2.validate();

        double[] y2Data = new double[angles.size()];
        for (int i = 0; i < angles.size(); i++) {
            y2Data[i] = angles.get(i)[2];
            xData[i] = i;

        }
        XYChart chart2 = QuickChart.getChart("Sample Chart", "X", "Y", "y(x)", xData, y2Data);// Show it
        JPanel panel2 = new XChartPanel<>(chart2);
        graphLayout3.setLayout(new BorderLayout());
        graphLayout3.add(panel2);
        graphLayout3.validate();
        
    }//GEN-LAST:event_plot3ActionPerformed

    private void plot3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plot3MouseEntered
        // TODO add your handling code here:
        Color clr1 = new Color(191,30,46);
        plot3.setBackground(clr1);
        plot3.setForeground(Color.white);
    }//GEN-LAST:event_plot3MouseEntered

    private void plot3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plot3MouseExited
        // TODO add your handling code here:
        Color clr1 = new Color(240,240,240);
        plot3.setBackground(clr1);
        plot3.setForeground(Color.black);
    }//GEN-LAST:event_plot3MouseExited

    private void plot4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plot4ActionPerformed
        // TODO add your handling code here:
        ;
        graphLayout3.validate();
    }//GEN-LAST:event_plot4ActionPerformed

    private void plot4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plot4MouseEntered
        // TODO add your handling code here:
        Color clr1 = new Color(191,30,46);
        plot4.setBackground(clr1);
        plot4.setForeground(Color.white);
    }//GEN-LAST:event_plot4MouseEntered

    private void plot4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plot4MouseExited
        // TODO add your handling code here:
        Color clr1 = new Color(240,240,240);
        plot4.setBackground(clr1);
        plot4.setForeground(Color.black);
    }//GEN-LAST:event_plot4MouseExited

    private void plot1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plot1MouseClicked

    }//GEN-LAST:event_plot1MouseClicked

    private void flexion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flexion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_flexion1ActionPerformed

    private void adduction1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adduction1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adduction1ActionPerformed

    private void rotation1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rotation1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rotation1ActionPerformed

    private void flexion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flexion2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_flexion2ActionPerformed

    private void adduction2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adduction2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adduction2ActionPerformed

    private void rotation2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rotation2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rotation2ActionPerformed

    private void flexion4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flexion4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_flexion4ActionPerformed

    private void adduction4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adduction4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adduction4ActionPerformed

    private void rotation4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rotation4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rotation4ActionPerformed

    private void flexion3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flexion3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_flexion3ActionPerformed

    private void adduction3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adduction3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adduction3ActionPerformed

    private void rotation3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rotation3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rotation3ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        //System.out.println(jComboBox1.getSelectedItem());
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserInterface1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserInterface1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserInterface1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserInterface1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserInterface1().setVisible(true);
            }
        });
    }
    public void graphPlot(String upper,String lower,String panelName){
        
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JRadioButton adduction1;
    private javax.swing.JRadioButton adduction2;
    private javax.swing.JRadioButton adduction3;
    private javax.swing.JRadioButton adduction4;
    private javax.swing.JLabel analyzeDataLabel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JPanel dashboard;
    private javax.swing.JRadioButton flexion1;
    private javax.swing.JRadioButton flexion2;
    private javax.swing.JRadioButton flexion3;
    private javax.swing.JRadioButton flexion4;
    private javax.swing.JPanel graphLayout1;
    private javax.swing.JPanel graphLayout2;
    private javax.swing.JPanel graphLayout3;
    private javax.swing.JPanel graphLayout4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton plot1;
    private javax.swing.JButton plot2;
    private javax.swing.JButton plot3;
    private javax.swing.JButton plot4;
    private javax.swing.JRadioButton rotation1;
    private javax.swing.JRadioButton rotation2;
    private javax.swing.JRadioButton rotation3;
    private javax.swing.JRadioButton rotation4;
    private javax.swing.JLabel selectFilesLabel;
    private javax.swing.JLabel subjectData;
    // End of variables declaration//GEN-END:variables

    private ImageIcon createImageIcon(String search_image_iconpng) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    
}
